Update the rest of the mk files from eng.git

diff --git a/tools/mk/Makefile.targ b/tools/mk/Makefile.targ
--- a/tools/mk/Makefile.targ
+++ b/tools/mk/Makefile.targ
@@ -1,39 +1,81 @@
-#
+
 # This Source Code Form is subject to the terms of the Mozilla Public
 # License, v. 2.0. If a copy of the MPL was not distributed with this
 # file, You can obtain one at http://mozilla.org/MPL/2.0/.
 #
 
 #
-# Copyright (c) 2017, Joyent, Inc.
+# Copyright 2020 Joyent, Inc.
+# Copyright 2023 MNX Cloud, Inc.
 #
 
 #
 # Makefile.targ: common targets.
 #
-# NOTE: This makefile comes from the "eng" repo. It's designed to be dropped
-# into other repos as-is without requiring any modifications. If you find
-# yourself changing this file, you should instead update the original copy in
-# eng.git and then update your repo to use the new version.
+
+#
+# NOTE: This makefile comes from the "eng" repo. If you find yourself changing
+# this file, you should ensure that you test all consumers of it, since
+# eng.git is a git submodule of several repositories. After testing, push
+# changes to the eng.git repository as normal, then do the following for
+# each component that uses eng.git, likely reusing the original ticket subject
+# for the commit message as was used for the eng.git push.
+#
+#    $ git submodule update --remote deps/eng
+#    $ git add deps/eng
+#    $ git commit -m "TOOLS-xxxx some description" deps/eng
+#
+# Then create a PR as usual for review.
+#
+
 #
 # This Makefile defines several useful targets and rules. You can use it by
 # including it from a Makefile that specifies some of the variables below.
 #
 # Targets defined in this Makefile:
 #
-#	check	Checks JavaScript files for lint and style
-#		Checks bash scripts for syntax
-#		Checks SMF manifests for validity against the SMF DTD
+#	bits-upload	Upload the bits produced by the component Makefile's
+#			'publish' target to Manta or a local filesystem,
+#			optionally publishing images to
+#			updates.tritondatacenter.com
 #
-#	clean	Removes built files
+#	bits-upload-latest
+#			As above, but use the bits/<component>/latest-build-stamp
+#			file to determine the $(STAMP) of the uploaded bits
 #
-#	docs	Builds restdown documentation in docs/
+#	buildimage	Builds an image
 #
-#	prepush	Depends on "check" and "test"
+#	check		- check-jsl: Check JavaScript lint with 'jsl'
+#			  See JSL_ vars below.
+#			- check-jsstyle: Check JavaScript style with 'jsstyle'.
+#			  See JSSTYLE_ vars below.
+#			- check-bash: Checks $BASH_FILES for style.
+#			- check-manifests: Checks SMF manifests for validity
+#			  against the SMF DTD. See "Makefile.smf.defs".
+#			- check-copyright: Checks "Copyright" statements in
+#			  files different from master. See
+#			  "ENGBLD_CHECK_COPYRIGHT_" vars below.
 #
-#	test	Does nothing (you should override this)
+#	clean		Removes built files
 #
-#	xref	Generates cscope (source cross-reference index)
+#	docs		Builds restdown documentation in docs/
+#
+#	prepublish	Is depended upon by "publish", saves the $(STAMP)
+#			of our last published bits, used by bits-upload.sh,
+#			as well as data about the build environment
+#
+#	prepush		Depends on "check" and "test"
+#
+#	show-buildenv	Emits the pkgsrc version required for this component,
+#			if available
+#
+#	test		Does nothing (you should override this)
+#
+#	validate-buildenv
+#			Runs a series of checks to determine if the build
+#			environment is valid for this component
+#
+#	xref		Generates cscope (source cross-reference index)
 #
 # For details on what these targets are supposed to do, see the Joyent
 # Engineering Guide.
@@ -69,6 +111,13 @@
 #
 #	JSSTYLE_FILES	JavaScript files to be style-checked
 #
+#	ENGBLD_CHECK_COPYRIGHT_DISABLE
+#			Set this to disable "check-copyright".
+#	ENGBLD_CHECK_COPYRIGHT_ARGS
+#			Arguments to pass invocations of "check-copyright".
+# 			Run the following to see available options:
+#			    make check-copyright ENGBLD_CHECK_COPYRIGHT_ARGS=-h
+#
 # You can also override these variables:
 #
 #	BASH		Path to bash (default: "bash")
@@ -78,6 +127,10 @@
 #
 #	CSCOPE_DIRS	Directories to search for source files for the cscope
 #			index. (default: ".")
+#
+#	ENGBLD_BITS_UPLOAD_OVERRIDE
+#			Set this to allow a component Makefile to declare its
+#			own 'bits-upload' and 'bits-upload-latest' targets
 #
 #	ESLINT		Path to eslint (default: "eslint")
 #
@@ -104,7 +157,9 @@
 # Defaults for the various tools we use.
 #
 BASH		?= bash
-BASHSTYLE   ?= $(NODE) tools/bashstyle
+BASHSTYLE   	?= $(NODE) deps/eng/tools/bashstyle
+ENGBLD_CHECK_COPYRIGHT ?= deps/eng/tools/check-copyright
+ENGBLD_CHECK_COPYRIGHT_ARGS ?= -q
 CP		?= cp
 CSCOPE		?= cscope
 CSCOPE_DIRS	?= .
@@ -130,7 +185,7 @@ endif
 # Defaults for other fixed values.
 #
 BUILD		?= build
-DISTCLEAN_FILES += $(BUILD)
+DISTCLEAN_FILES += $(BUILD) bits
 DOC_BUILD	= $(BUILD)/docs/public
 
 #
@@ -175,8 +230,11 @@ deps/%/.git:
 # would invoke bash with zero files), and you can check individual files from
 # the command line with "make filename.bashchk".
 #
+# Since bashstyle is a node program, we need our node runtime as a dependency
+# for running $(BASHSTYLE)
+#
 .PHONY: check-bash
-check-bash: $(BASH_FILES:%=%.bashchk) $(BASH_FILES:%=%.bashstyle)
+check-bash: $(NODE_EXEC) $(BASH_FILES:%=%.bashchk) $(BASH_FILES:%=%.bashstyle)
 
 %.bashchk: %
 	$(BASH) -n $^
@@ -221,8 +279,13 @@ JSSTYLE_TARGET = $(if $(JSSTYLE_FILES), check-jsstyle)
 check-jsstyle:  $(JSSTYLE_EXEC)
 	$(JSSTYLE) $(JSSTYLE_FLAGS) $(JSSTYLE_FILES)
 
+_CHECK_COPYRIGHT_TARGET = $(if $(ENGBLD_CHECK_COPYRIGHT_DISABLE),,check-copyright)
+.PHONY: check-copyright
+check-copyright:
+	$(ENGBLD_CHECK_COPYRIGHT) $(ENGBLD_CHECK_COPYRIGHT_ARGS)
+
 .PHONY: check
-check:: $(ESLINT_TARGET) check-jsl check-json $(JSSTYLE_TARGET) check-bash
+check:: $(ESLINT_TARGET) check-jsl check-json $(JSSTYLE_TARGET) check-bash $(_CHECK_COPYRIGHT_TARGET)
 	@echo check ok
 
 .PHONY: clean
@@ -332,6 +395,199 @@ test:
 prepush: check test
 
 #
+# Ensure we have a sane build environment. The script includes an escape
+# hatch in case of emergencies. set ENGBLD_SKIP_VALIDATE_BUILDENV=true in the
+# environment to have it always pass.
+#
+.PHONY: validate-buildenv
+validate-buildenv:
+	ENGBLD_SKIP_VALIDATE_BUILDENV=$(ENGBLD_SKIP_VALIDATE_BUILDENV) \
+	   $(TOP)/deps/eng/tools/validate-buildenv.sh
+
+.PHONY: show-buildenv
+show-buildenv:
+	@$(TOP)/deps/eng/tools/validate-buildenv.sh -r
+
+#
+# Everything should depend on us having a valid build environment.
+#
+all release publish buildimage: validate-buildenv
+
+publish: prepublish
+
+#
+# Store some information about the build environment. The latest-build-stamp
+# file is used if running the 'bits-upload-latest' target. See bits-upload.sh.
+# When generating npm-ls.json output, we ignore errors since older versions
+# of npm seem to sometimes install packages that /opt/tools/bin/npm deems
+# "invalid". That shouldn't be allowed to fail the build.
+#
+.PHONY: prepublish
+prepublish:
+	-mkdir -p $(ENGBLD_BITS_DIR)/$(NAME)
+	echo $(STAMP) > $(ENGBLD_BITS_DIR)/$(NAME)/latest-build-stamp
+	@echo "Generating $(ENGBLD_BITS_DIR)/$(NAME)/build-environment"
+	@if [[ "$$(uname -s)" == "SunOS" ]]; then \
+		MAKE_PID=$$(/usr/bin/ps -o ppid= -p $$$$); \
+		BUILD_IMG_UUID=$$($(PFEXEC) /usr/sbin/mdata-get sdc:image_uuid); \
+		echo hostname: $$(/usr/bin/hostname) > $(ENGBLD_BITS_DIR)/$(NAME)/build-environment; \
+		/usr/bin/cat /etc/pkgsrc_version >> $(ENGBLD_BITS_DIR)/$(NAME)/build-environment; \
+		echo image_uuid: $$BUILD_IMG_UUID >> $(ENGBLD_BITS_DIR)/$(NAME)/build-environment; \
+	fi
+	@echo "Generating $(ENGBLD_BITS_DIR)/$(NAME)/npm-ls.json"
+	-/opt/tools/bin/npm ls --json > $(ENGBLD_BITS_DIR)/$(NAME)/npm-ls.json
+
+
+#
+# Transform the boolean into the appropriate cli flag
+#
+ifdef BUILDIMAGE_DO_PKGSRC_UPGRADE
+BUILDIMAGE_DO_PKGSRC_UPGRADE_ARGS=-u
+endif
+
+
+#
+# The list of pkgsrc packages that should be installed in the
+# image that the 'buildimage' target constructs. Set here rather than
+# in Makefile.defs to ensure it's always computed after $(BUILDIMAGE_PKGSRC)
+# is set.
+#
+ifdef BUILDIMAGE_PKGSRC
+BUILDIMAGE_PKGSRC_ARGS = -p $$(echo $(BUILDIMAGE_PKGSRC) | sed -e 's/ /,/g')
+else
+BUILDIMAGE_PKGSRC_ARGS =
+endif
+
+#
+# If buildimage should not create an etc/motd file for the image, set
+# BUILDIMAGE_SKIP_MOTD.
+#
+ifndef BUILDIMAGE_SKIP_MOTD
+BUILDIMAGE_MOTD_ARGS = -M -S "$$(git -C $(TOP) remote get-url origin)"
+else
+BUILDIMAGE_MOTD_ARGS =
+endif
+
+#
+# BUILDIMAGE_PKG should nearly always be set to $(TOP)/$(RELEASE_TARBALL),
+# but ensure RELEASE_TARBALL is set before setting that default.
+#
+ifeq ($(ENGBLD_USE_BUILDIMAGE), true)
+
+ifndef BUILDIMAGE_PKG
+  ifndef RELEASE_TARBALL
+    $(error "Error: RELEASE_TARBALL must be set before including Makefile.targ")
+  else
+    BUILDIMAGE_PKG=$(TOP)/$(RELEASE_TARBALL)
+  endif
+endif
+
+endif
+
+#
+# We add a guard to ensure that users haven't invoked 'make buildimage'
+# by accident. It's better to bail out early with an clear error message
+# if a user has not declared that their component should $ENGBLD_USE_BUILDIMAGE.
+#
+.PHONY: buildimage
+buildimage: stamp-buildimage-prep release $(AGENTS:%=%-prebuilt)
+	if [[ "$(ENGBLD_USE_BUILDIMAGE)" != "true" ]]; then \
+		echo "This component is not configured to use buildimage."; \
+		echo "Set 'ENGBLD_USE_BUILDIMAGE=true' in the component Makefile otherwise."; \
+		exit 1; \
+	fi
+	mkdir -p $(ENGBLD_BITS_DIR)/$(NAME)
+	mkdir -p $(BUILDIMAGE_STAGEDIR)
+	cd $(BUILDIMAGE_STAGEDIR) ; \
+	$(TOP)/deps/eng/tools/buildimage-extract-pkg.sh $(BUILDIMAGE_PKG)
+	$(PFEXEC) chown -R root:root $(BUILDIMAGE_STAGEDIR)
+	cd $(BUILDIMAGE_STAGEDIR); \
+	BUILDIMAGE=$$(cat $(TOP)/$(STAMP_BUILDIMAGE_PREP)); \
+	$(PFEXEC) $$BUILDIMAGE \
+		-i $(BASE_IMAGE_UUID) \
+		-d $(BUILDIMAGE_STAGEDIR)/root \
+		-m '$(BUILDIMAGE_MF)' \
+		$(BUILDIMAGE_DO_PKGSRC_UPGRADE_ARGS) \
+		$(BUILDIMAGE_PKGSRC_ARGS) \
+		$(BUILDIMAGE_MOTD_ARGS) \
+		-a \
+		-P $(NAME)-zfs
+	cp /tmp/$(NAME)-zfs-$(BUILDIMAGE_VERSION).zfs.gz $(ENGBLD_BITS_DIR)/$(NAME)
+	cp /tmp/$(NAME)-zfs-$(BUILDIMAGE_VERSION).imgmanifest $(ENGBLD_BITS_DIR)/$(NAME)
+	cp /tmp/$(NAME)-zfs-$(BUILDIMAGE_VERSION).pkgaudit $(ENGBLD_BITS_DIR)/$(NAME)
+	$(PFEXEC) rm /tmp/$(NAME)-zfs-$(BUILDIMAGE_VERSION).zfs.gz
+	$(PFEXEC) rm /tmp/$(NAME)-zfs-$(BUILDIMAGE_VERSION).imgmanifest
+	$(PFEXEC) rm /tmp/$(NAME)-zfs-$(BUILDIMAGE_VERSION).pkgaudit
+	$(PFEXEC) rm -rf $(BUILDIMAGE_STAGEDIR)
+
+#
+# Upload the build products from this component's ./bits directory
+# to either manta or a filesystem path. We allow consumers to override
+# this, supplying their own custom bits-upload* targets by setting
+# ENGBLD_BITS_UPLOAD_OVERRIDE.
+#
+ifndef ENGBLD_BITS_UPLOAD_OVERRIDE
+.PHONY: bits-upload
+bits-upload: publish $(BUILDIMAGE_TARG)
+	$(TOP)/deps/eng/tools/bits-upload.sh \
+		-b "$(BRANCH)" \
+		-B "$(TRY_BRANCH)" \
+		$(BITS_UPLOAD_LOCAL_ARG) \
+		$(BITS_UPLOAD_IMGAPI_ARG) \
+		-d $(ENGBLD_DEST_OUT_PATH)/$(NAME) \
+		-D $(ENGBLD_BITS_DIR) \
+		-n $(NAME) \
+		-t $(STAMP)
+
+#
+# A convenience target that doesn't require us to do a full build. We derive
+# the timestamp for the bits being uploaded from the latest-build-stamp file
+# in build/bits directory, produced by the 'prepublish' target.
+#
+.PHONY: bits-upload-latest
+bits-upload-latest:
+	$(TOP)/deps/eng/tools/bits-upload.sh \
+		-b "$(BRANCH)" \
+		-B "$(TRY_BRANCH)" \
+		$(BITS_UPLOAD_LOCAL_ARG) \
+		$(BITS_UPLOAD_IMGAPI_ARG) \
+		-d $(ENGBLD_DEST_OUT_PATH)/$(NAME) \
+		-D $(ENGBLD_BITS_DIR) \
+		-n $(NAME)
+endif
+
+#
+# Determine whether we need to build buildimage, or use the copy in
+# /opt/tools. Write the path to $(STAMP_BUILDIMAGE_PREP) for later
+# use in the 'buildimage' target. We use a crude version comparison here,
+# choosing the deps/eng copy if it's different to the copy in /opt/tools.
+#
+$(STAMP_BUILDIMAGE_PREP): $(TOP)/deps/eng/tools/buildimage/package.json
+	$(MAKE_STAMP_REMOVE)
+	if [[ -n "$(ENGBLD_FORCE_LOCAL_BUILDIMAGE)" ]]; then \
+		LOCAL_BUILDIMAGE=true; \
+	elif [[ ! -f /opt/tools/bin/buildimage ]]; then \
+		LOCAL_BUILDIMAGE=true; \
+	else \
+		LOCAL_BUILDIMAGE_VER=$$( \
+		    json -f $(TOP)/deps/eng/tools/buildimage/package.json version); \
+		TOOLS_BUILDIMAGE_VER=$$( \
+		    json -f \
+		        /opt/tools/lib/node_modules/buildimage/package.json version); \
+		if [[ "$$LOCAL_BUILDIMAGE_VER" != "$$TOOLS_BUILDIMAGE_VER" ]]; then \
+		    LOCAL_BUILDIMAGE=true; \
+		fi; \
+	fi; \
+	if [[ -n "$$LOCAL_BUILDIMAGE" ]]; then \
+		echo $(TOP)/deps/eng/tools/buildimage/bin/buildimage > \
+		    $(STAMP_BUILDIMAGE_PREP); \
+		cd $(TOP)/deps/eng/tools/buildimage; \
+		$(MAKE) buildimage-prep; \
+	else \
+		echo /opt/tools/bin/buildimage > $(STAMP_BUILDIMAGE_PREP); \
+	fi;
+
+#
 # This rule automatically exposes every "stamp" file as a target that can be
 # invoked manually as "stamp-$STAMP_NAME".  For example, if a stamp has been
 # defined thus:
@@ -346,3 +602,10 @@ prepush: check test
 #
 stamp-%: $(MAKE_STAMPS_DIR)/%
 	@:
+
+#
+# Allow for easier Makefile debugging. 'make print-FOO' will emit the value
+# of $(FOO).
+#
+print-%:
+	@echo '$*=$($*)'
